apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: synapse-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /synapse
spec:
  rules:
    - http:
        paths:
          - path: /synapse
            pathType: Prefix
            backend:
              service:
                name: synapse
                port:
                  number: 8080
