logging:
  level:
    org:
      hibernate:  
        SQL: debug
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/synapse
    driver-class-name: org.postgresql.Driver
    username: synapse
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update   # o create-drop si quieres recrear cada vez
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB     # Tama침o m치ximo de cada archivo
      max-request-size: 10MB   # Tama침o m치ximo de la solicitud
server:
  servlet:
    context-path: @project.contextPath@
project:
  jwt:
    signKey: WzROun12eUiDvko3UrJ74gNeJz2TWEWPMTh6DxyE8HWXIf4hETUrkM4IUGqqHq66PuVS
    expirationMinutes: 1440
  claude:
    apiKey: ${CLAUDE_API_KEY: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}
    apiUrl: https://api.anthropic.com/v1/messages
    model: claude-3-5-sonnet-20241022

